GET http://localhost:4000/users

###

POST http://localhost:4000/register
Content-Type: application/json

{
"username": "ravi",
"password": "password"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
"username": "ravi",
"password": "password"
}

###

GET http://localhost:4000/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdmkiLCJpYXQiOjE2MzY4MTIzNjh9.EueS75ldXJmx3xgtVB0pfEFPYF0BiCSW4qn6IceatoM